Models/Satislar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satislar()
        {
            this.Faturalar = new HashSet<Faturalar>();
            this.UrunSatis = new HashSet<UrunSatis>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> ToplamBorc { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> MusteriId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faturalar> Faturalar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunSatis> UrunSatis { get; set; }
    }
}

Controllers/FaturalarController.cs
using FinansApp.Managers;
using FinansApp.Models;
using FinansApp.SessionFilter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinansApp.Controllers
{
    [AdminSessionControlFilter]
    public class FaturalarController : Controller
    {
        // GET: Faturalar
        FaturalarManager mng = new FaturalarManager();
        SatislarManager mngSatis = new SatislarManager();
        MusteriManager mngMusteri = new MusteriManager();
        public ActionResult Index(int MusteriId=0,string adi="")
        {
            Musteriler musteri= mngMusteri.GetById(MusteriId);
            TempData["adi"] = adi;
            ViewData["MusteriId"] = MusteriId;
            if (musteri != null)
                TempData["AdiSoyadi"] = musteri.AdiSoyadi;
            IEnumerable<Faturalar> lstMus = null;
            if(MusteriId!=0)
            {
            lstMus = mng.GetByMusteriId(MusteriId);
            }
            else if(adi!="")
            {
                lstMus = mng.GetByMusteriAdi(adi);
            }
            else
            {
                lstMus = mng.GetList();
            }
                
            return View(lstMus);
        }
        public ActionResult FaturaKes(int MusteriId, int SatisId)
        {
            Musteriler musteri = mngMusteri.GetById(MusteriId);
            Satislar satis = mngSatis.GetById(SatisId);
            Faturalar fatura = new Faturalar();
            fatura.SatisId = SatisId;
            fatura.Tarih = DateTime.Now;
            fatura.Tutar = satis.Odenen;
            Faturalar fat = mng.GetBySatisld(SatisId);
            if (fat == null)
                fatura = mng.InsertOrUpdate(fatura);
            else
                fatura = fat;

            //ViewData["MusteriId"] = MusteriId;
            //ViewData["BorcId"] = BorcId;
            //TempData["AdiSoyadi"] = musteri.AdiSoyadi;
            //if (musteri == null)
            //    return RedirectToAction("Index", "Musteriler");
            //Faturalar borc = mng.GetById(id);
            return RedirectToAction("FaturaDetay", new { id= fatura.Id });
        }
        public ActionResult FaturaDetay(int id)
        {
            Faturalar fatura = mng.GetById(id);
            List<UrunSatis> lst = fatura.Satislar.UrunSatis.ToList();
            TempData["SatisId"] = fatura.SatisId;
            TempData["AdiSoyadi"] = fatura.Satislar.Musteriler.AdiSoyadi;
            return View(lst);
        }
        //public ActionResult Kayit(int MusteriId,int BorcId,int id = 0)
        //{
        //    Musteriler musteri = mngMusteri.GetById(MusteriId);
        //    ViewData["MusteriId"] = MusteriId;
        //    ViewData["BorcId"] = BorcId;
        //    TempData["AdiSoyadi"] = musteri.AdiSoyadi;
        //    if (musteri == null)
        //        return RedirectToAction("Index", "Musteriler");
        //    Faturalar borc = mng.GetById(id);
        //    return View(borc);
        //}
        //[HttpPost]
        //public ActionResult Kayit(Faturalar Faturalar)
        //{
        //    Faturalar = mng.InsertOrUpdate(Faturalar);
        //    return RedirectToAction("Index");
        //}
        public ActionResult Sil(int id)
        {
            mng.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/SatislarController.cs
using FinansApp.Managers;
using FinansApp.Models;
using FinansApp.SessionFilter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinansApp.Controllers
{
    [AdminSessionControlFilter]
    public class SatislarController : Controller
    {
        // GET: Satislar
        SatislarManager mngSatislar = new SatislarManager();
        MusteriManager mngMusteri = new MusteriManager();
        UrunSatisManager mngUrunSatis = new UrunSatisManager();
        UrunlerManager mngUrunler = new UrunlerManager();
        public ActionResult Index(int MusteriId=0,string tum1Borc2="1")
        {
            TempData["Musteriler"] = mngMusteri.GetList();
            Musteriler musteri = null;
            if(MusteriId!=0)
            {
                musteri = mngMusteri.GetById(MusteriId);
                ViewData["MusteriId"] = MusteriId;
            }
          
            if (musteri != null)
                TempData["AdiSoyadi"] = musteri.AdiSoyadi;
            IEnumerable<Satislar> lstMus = null;
            if(MusteriId==0)
            {
                lstMus = mngSatislar.GetList();
                
            }
            
            else
                lstMus = mngSatislar.GetListByMusteriId(MusteriId);
            if (tum1Borc2 == "2")
            {
                lstMus=lstMus.Where(x => x.Odenen < x.ToplamBorc).ToList();
            }
            else if(tum1Borc2=="3")
            {
                lstMus = lstMus.Where(x => x.Odenen == x.ToplamBorc).ToList();
            }
            TempData["borc"] = tum1Borc2;
            return View(lstMus);
        }
        public ActionResult Kayit(int MusteriId)
        {
            Musteriler musteri = mngMusteri.GetById(MusteriId);
            TempData["MusteriId"] = MusteriId;
            TempData["AdiSoyadi"] = musteri.AdiSoyadi;
            Satislar satis = new Satislar();
            satis.Tarih = DateTime.Now;
            satis.MusteriId = MusteriId;
            satis.Odenen = 0;
            satis.ToplamBorc = 0;
            
            satis = mngSatislar.InsertOrUpdate(satis);
            return RedirectToAction("Satis",new { SatisId=satis.Id });
            //Musteriler musteri = mngMusteri.GetById(MusteriId);
            //TempData["MusteriId"] = MusteriId;
            //TempData["AdiSoyadi"] = musteri.AdiSoyadi;
            //if (musteri == null)
            //    return RedirectToAction("Index", "Musteriler");
            //Satislar borc = mng.GetById(id);
            //return View(borc);
        }
        [HttpPost]
        public ActionResult Kayit(Satislar Satislar)
        {
            Satislar = mngSatislar.InsertOrUpdate(Satislar);
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id,int SatisId = 0)
        {
            TempData["hata"] = "";
            TempData["sonuc"] = "";
            mngSatislar.Delete(id);
            if(mngSatislar.GetError().HasError)
            {
                TempData["hata"] = "Bu satışa ait bit çok ürün var.Satıs Detay sayfasından eklenmiş ürünleri silmelisiniz!";
             
            }
           // mngUrunSatis.Delete(id);
            if(SatisId == 0)
            return RedirectToAction("Index");
            return RedirectToAction("Satis",new { SatisId = SatisId });
        }
        public ActionResult UrunSil(int id, int SatisId = 0)
        {
            //mngSatislar.Delete(id);
            mngUrunSatis.Delete(id);
            if (SatisId == 0)
                return RedirectToAction("Index");
            return RedirectToAction("Satis", new { SatisId = SatisId });
        }
        public ActionResult Satis(int SatisId=0)
        {
            if (SatisId == 0)return RedirectToAction("Index");
            ViewData["Urunler"] = mngUrunler.GetList();
           
            TempData["SatisId"] = SatisId;
            Satislar satislar = mngSatislar.GetById(SatisId);
            ViewData["Odenen"] = satislar.Odenen;
            TempData["MusteriId"] = satislar.MusteriId;
            TempData["AdiSoyadi"] = satislar.Musteriler.AdiSoyadi;
            IEnumerable<UrunSatis> lst = mngUrunSatis.GetListBySatisId(SatisId);
            return View(lst);
        }
        [HttpPost]
        public ActionResult Odeme(decimal Odenen,int SatisID)
        {
            Satislar satis = mngSatislar.GetById(SatisID);
            TempData["hata"] = "";
            TempData["sonuc"] = "";
            if (satis==null)
            {
                TempData["hata"] = "Satıs işleminde bir sorun oluştu";
                return RedirectToAction("Index");
            }
            if (satis.Odenen == null) satis.Odenen = 0;
            satis.Odenen += Odenen;
            if(satis.Odenen>satis.ToplamBorc)
            {
                TempData["hata"] = "Ödeme toplam tutarı gecemez!";
                return RedirectToAction("Satis", new { SatisId = SatisID });
            }
            mngSatislar.InsertOrUpdate(satis);
            if(!mngSatislar.GetError().HasError)
            TempData["sonuc"] = "Ödeme işlemi Başarılı";
            else
                TempData["hata"] = mngSatislar.GetError().ErrorMessage;
            return RedirectToAction("Satis", new { SatisId = SatisID });
        }
        [HttpPost]
        public ActionResult UrunSatis(UrunSatis uSatis)
        {
            //ViewData["Urunler"] = mngUrunler.GetList();
            //ViewData["SatisId"] = satisSatisId;
            //IEnumerable<UrunSatis> lst = mngUrunSatis.GetListBySatisId(SatisId);
            uSatis=mngUrunSatis.InsertOrUpdate(uSatis);
            return RedirectToAction("Satis",new { SatisId=uSatis.SatisId });
        }
    }
}

Views/Satislar/Index.cshtml
@model IEnumerable<FinansApp.Models.Satislar>
@{
    ViewBag.Title = "Satışlar";
}


<br />
@{
    List<FinansApp.Models.Musteriler> lstMusteri = (List<FinansApp.Models.Musteriler>)TempData["Musteriler"];
    lstMusteri.Add(new FinansApp.Models.Musteriler() { AdiSoyadi = "Lütfen Müşteri seçiniz", Id = 0 });

}


<h2>
    Arama
    
</h2>
<hr />
<div class="col-md-12">
    <div class="col-md-1">
        <a class="btn btn-primary" onclick="git()"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bul&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </a>
    </div>
    <div class="col-md-3">
        @Html.DropDownListFor(model => model.FirstOrDefault().MusteriId, new SelectList(lstMusteri.OrderBy(x => x.Id).ToList(), "Id", "AdiSoyadi"), new { @class = "form-control" })

    </div>
    <div class="col-md-7">
        @if (TempData["borc"] != null && TempData["borc"].ToString() == "1")
        {
            <input type="radio" name="rb" value="1" checked="checked" id="rb1" /><label for="male">Tüm Kayıtlar</label>
            <input type="radio" name="rb" value="2" id="rb2" /><label for="rb">Borclular</label>
            <input type="radio" name="rb" value="3" id="rb3" /><label for="rb">Borcu Olmayanlar</label>
        }
        else if (TempData["borc"] != null && TempData["borc"].ToString() == "2")
        {
            <input type="radio" name="rb" value="1" id="rb1" /><label for="male">Tüm Kayıtlar</label>
            <input type="radio" name="rb" value="2" checked="checked" id="rb2" /><label for="rb">Borclular</label>
            <input type="radio" name="rb" value="3" id="rb3" /><label for="rb">Borcu Olmayanlar</label>
        }
        else
        {
            <input type="radio" name="rb" value="1" id="rb1" /><label for="male">Tüm Kayıtlar</label>
            <input type="radio" name="rb" value="2"  id="rb2" /><label for="rb">Borclular</label>
            <input type="radio" name="rb" value="3" checked="checked" id="rb3" /><label for="rb">Borcu Olmayanlar</label>
        }

    </div>
</div>
<br />
<h2>
    Satışlar
    @if (TempData["AdiSoyadi"] != null)
    {
        @("("+TempData["AdiSoyadi"]+")")
    }
</h2>
<hr />
@if (ViewData["MusteriId"] != null)
{
    <div class="col-md-12">
        <div class="col-md-2">
            @Html.ActionLink("Yeni Satış", "Kayit", new { MusteriId = ViewData["MusteriId"] }, new { @class = "btn btn-primary" })
        </div>


    </div>

}

<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Adı Soyadı</th>
            <th scope="col">Tarih</th>
            <th scope="col">Toplam Tutar</th>
            <th scope="col">Ödenen</th>
            <th scope="col">Kalan</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">@(i++)</td>
                <td>@item.Musteriler.AdiSoyadi</td>
                <td>@item.Tarih.Value.ToString("dd.MM.yyyy")</td>,
                <td><span class="bg-warning">@(item.ToplamBorc!= null?item.ToplamBorc.Value.ToString()+" ₺":"0"+" ₺")</span></td>
                <td><span class="bg-success">@(item.Odenen.Value.ToString()+" ₺")</span></td>
                <td><span class="bg-danger">@((item.ToplamBorc != null ? (item.ToplamBorc.Value - item.Odenen.Value)+"":"0").ToString()+" ₺")</span> </td>
                <td>@Html.ActionLink("Satış Detayı", "Satis", new { SatisId = item.Id })</td>
                <td>
                    @if ((item.Faturalar == null || item.Faturalar.Count == 0) && item.ToplamBorc == item.Odenen && item.Odenen != 0)
                    {
                        @Html.ActionLink("Fatura Kes", "FaturaKes", "Faturalar", new { MusteriId = item.MusteriId, SatisId = item.Id }, new { })
                    }
                    else if ((item.Faturalar != null && item.Faturalar.Count > 0))
                    {
                        @Html.ActionLink("Faturayı Gör", "FaturaDetay", "Faturalar", new { id = item.Faturalar.FirstOrDefault().Id }, new { })
                    }
                    else
                    {
                        <span class="alert-danger">Ödeme Tamamlanmamış</span>
                    }

                </td>
                <td>
                    @Html.ActionLink("Sil", "Sil", new { id = item.Id, MusteriId = item.MusteriId })
                </td>
            </tr>
        }


    </tbody>
</table>
<input type="hidden" name="sonuc" id="sonuc" value="@TempData["sonuc"]" />
<input type="hidden" name="hata" id="hata" value="@TempData["hata"]" />
<script type="text/javascript">
    function git() {
        var mId = $("#MusteriId").val();
        if (mId != "" && mId != undefined && mId != null && mId != "0") {
            window.location = "/Satislar/Index?MusteriId=" + $("#MusteriId").val() +"&tum1Borc2=" + $('input[name="rb"]:checked').val();
        }
        else {
            window.location = "/Satislar/Index?MusteriId=0&tum1Borc2=" + $('input[name="rb"]:checked').val();
        }

    }
    $(document).ready(function () {
        var mesaj = $("#sonuc").val();
        var hata = $("#hata").val();
        if (mesaj != "") {
            $("#titleMessageBoxModal").html("Ödeme İşlemi");
            $("#pMessageBoxModal").html(mesaj);
            $("#MessageBoxModal").modal();
        }
        else if (hata != "") {
            $("#titleMessageBoxModal").html("Bir Hata Meydana Geldi");
            $("#pMessageBoxModal").html(hata);
            $("#MessageBoxModal").modal();
        }

    });
</script>

Views/Satislar/Kayit.cshtml
@model FinansApp.Models.Satislar

@{
    ViewBag.Title = "Kayit";
}

<h2>Kayit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Borclar</h4>
    <hr />
   
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Musteriler.AdiSoyadi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@if (Model.Musteriler != null)
            {
                @Html.EditorFor(model => model.Musteriler.AdiSoyadi, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            }
            else
            {*@
                <input readonly="readonly" class = "form-control" value="@TempData["AdiSoyadi"]"/>
            @*}*@

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ToplamBorc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ToplamBorc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ToplamBorc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Odenen, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Odenen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Odenen, "", new { @class = "text-danger" })
        </div>
        @Html.HiddenFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
        @Html.HiddenFor(model => model.MusteriId, new { htmlAttributes = new { @class = "form-control" } })
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Tarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarih, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarih, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Satış Listesi", "Index")
</div>

Views/Satislar/Satis.cshtml
@model IEnumerable<FinansApp.Models.UrunSatis>
@{
    ViewBag.Title = "Satış Detayı";
}
@{
    int i = 1;
    decimal toplamTutar = 0;
    int satId = Convert.ToInt32(TempData["SatisId"]);
    decimal odenen = Convert.ToDecimal(ViewData["Odenen"]);
    toplamTutar = Model.Where(x => x.SatisId == satId).Sum(x => x.AraToplam).Value;
}
<h2>
    Satış İşlemi  (TOPLAM TUTAR: @(toplamTutar+" ₺"))

</h2>
<h3>
    <b>
        Müsteri Adı :
    </b>
    @if (TempData["AdiSoyadi"] != null)
    {
        @(TempData["AdiSoyadi"])
    }
</h3>
<h3>
    <b>
        Tarih :
    </b>
    @if (Model.Count() > 0)
    {
        @(Model.First().Satislar.Tarih.Value.ToString("dd.MM.yyyy"))
    }
</h3>

<br />
<button type="button" onclick="temizle()" class="btn btn-primary" data-toggle="modal" data-target="#ModalSatis" data-whatever="@@mdo">Ürün Ekle</button>
@*@Html.ActionLink("Yeni Kayıt", "Kayit", new { MusteriId = ViewData["MusteriId"] }, new { @class = "btn btn-primary" })*@
<br />

<table class="table">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Ürün Adı</th>
            <th scope="col">Adet</th>
            <th scope="col">Birim Fiyat</th>
            <th scope="col">Ara Toplam</th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">@(i++)</td>
                <td>@item.Urunler.Ad</td>
                <td>@item.Adet</td>
                <td>@(item.Urunler.Fiyat.Value.ToString() + " ₺")</td>
                <td>@((item.Urunler.Fiyat.Value * item.Adet).ToString() + " ₺")</td>
                <td>
                    <a onclick="openModal(@item.Id,@item.UrunId,@item.Adet)">Düzenle</a>
                </td>
                <td>@Html.ActionLink("Sil", "UrunSil", new { id = item.Id, SatisId = item.Satislar.Id })</td>
            </tr>
        }
        <tr>
            <td scope="row"></td>
            <td></td>
            <td></td>
            <td><b>TOPLAM TUTAR:</b></td>
            <td> <b>@(toplamTutar.ToString()+" ₺") </b></td>
            @*<td>@Html.ActionLink("Düzenle", "SatisYap", new { id = item.Id })</td>*@
            <td>(Toplam Ödenen:@(odenen.ToString()+" ₺")</td>
            <td> Kalan:@((toplamTutar-odenen).ToString()+" ₺")) </td>

        </tr>

    </tbody>
</table>
@{
    List<FinansApp.Models.Urunler> lstUrn = (List<FinansApp.Models.Urunler>)ViewData["Urunler"];
}
<div class="modal fade" id="ModalSatis" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("UrunSatis", "Satislar"))
        {
            @Html.AntiForgeryToken()
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        Satış İşlemi
                        @if (TempData["AdiSoyadi"] != null)
                        {
                            @(" ("+TempData["AdiSoyadi"]+")")
                        }
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Ürün:</label>
                            @Html.DropDownListFor(model => model.FirstOrDefault().UrunId, new SelectList(lstUrn, "Id", "Ad"), new { @class = "form-control" })
                            @*<input type="text" class="form-control" id="AdiSoyadi" name="AdiSoyadi">*@
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Adet:</label>
                            @Html.EditorFor(model => model.FirstOrDefault().Adet, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                            <input type="hidden" id="SatisId" name="SatisId" value="@TempData["SatisId"]" />
                            <input type="hidden" id="Id" name="Id" value="@TempData["SatisId"]" />
                        </div>
                        @*<div class="form-group">
                                <label for="message-text" class="col-form-label">Message:</label>
                                <textarea class="form-control" id="message-text"></textarea>
                            </div>*@
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>
            </div>
        }
    </div>
</div>
<div class="modal fade" id="ModalOdeme" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Odeme", "Satislar"))
        {
            @Html.AntiForgeryToken()
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        Satış İşlemi
                        @if (TempData["AdiSoyadi"] != null)
                        {
                            @(" ("+TempData["AdiSoyadi"]+")")
                        }
                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label"><b>Ödenmesi Gereken Toplam tutar: @(toplamTutar+" ₺") </b> </label>

                            <input type="text" class="form-control" id="Odenen" name="Odenen" value="@(toplamTutar-odenen)">
                            <input type="hidden" id="SatisID" name="SatisID" value="@TempData["SatisId"]" />
                        </div>
                        @*<div class="form-group">
                                <label for="recipient-name" class="col-form-label">Adet:</label>



                            </div>*@
                        @*@Html.EditorFor(model => model.FirstOrDefault()., new { htmlAttributes = new { @class = "form-control", @type = "number" } })*@
                        @*<div class="form-group">
                                <label for="message-text" class="col-form-label">Message:</label>
                                <textarea class="form-control" id="message-text"></textarea>
                            </div>*@
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
                    <button type="submit" class="btn btn-primary">Kaydet</button>
                </div>
            </div>
        }
    </div>
</div>
@if ((toplamTutar - odenen) == 0&&toplamTutar>0)
{
    @Html.ActionLink("Fatura Kes", "FaturaKes", "Faturalar",new { MusteriId=Model.FirstOrDefault().Satislar.Musteriler.Id, SatisId= Model.FirstOrDefault().Satislar.Id},new { @class="btn btn-primary"})
}
else
{
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalOdeme" data-whatever="@@mdo">Ödeme Yap</button>
}
<br />
<br />
<br />
<input type="hidden" name="sonuc" id="sonuc" value="@TempData["sonuc"]" />
<input type="hidden" name="hata" id="hata" value="@TempData["hata"]" />


<div>
    @if (TempData["MusteriId"] != null)
    {
        @Html.ActionLink("Listeye Dön", "Index",new { MusteriId= TempData["MusteriId"] .ToString()})
    }
    else
    {
        @Html.ActionLink("Listeye Dön", "Index")
    }

</div>

<script type="text/javascript">
    $(document).ready(function () {
        var mesaj = $("#sonuc").val();
        var hata = $("#hata").val();
        if (mesaj != "") {
            $("#titleMessageBoxModal").html("Ödeme İşlemi");
            $("#pMessageBoxModal").html(mesaj);
            $("#MessageBoxModal").modal();
        }
        else if (hata != "") {
            $("#titleMessageBoxModal").html("Ödeme İşlemi Hatası");
            $("#pMessageBoxModal").html(hata);
            $("#MessageBoxModal").modal();
        }

    });

    function temizle() {
        $("#UrunId").val("");
        $("#Adet").val(1);
        $("#Id").val(0);
    }

    function openModal(id, urunId, adet) {
        $("#Id").val(id);
        $("#UrunId").val(urunId);
        $("#Adet").val(adet);
        $("#ModalSatis").modal();
    }
</script>